services:
- postgresql
before_script:
 - psql -c 'create database tecservice;' -U postgres
 - psql -U postgres -d tecservice -f script/create_tables.sql
 - cd src/TeCService
 - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
